### ISSUE TITLE
Dsyms upload ignores configuration

### ISSUE THREAD

**Issue by Nicktho** [DataDog/expo-datadog#3]
**Describe what happened**
Setting configuration to the following:

```
{
    "expo": {
        "plugins": [
            [
                "expo-datadog",
                {
                    "errorTracking": {
                        "iosDsyms": false
                    }
                }
            ]
        ]
    }
}
```

Still results in dsyms being uploaded to datadog when running `expo run:ios` to build the ios application.

**Steps to reproduce the issue:**
* Add above configuration to `app.json`
* Run a local ios build: `expo run:ios`
* Observe dsyms uploaded to datadog, or an error with an incorrect api key.

**Describe what you expected:**
Dsyms not uploaded to datadog

**Additional context**

- Version of the Expo SDK
- Versions of `expo-datadog` and `@datadog/mobile-react-native`
- `app.json`
- `eas.json` if relevant
- `package.json`
- `Podfile` and `Podfile.lock`
- `android/build.gradle` and `android/app/build.gradle`

**Comment by louiszawadzki** [comment]
Hi @Nicktho, thanks for reaching out and apologies for the delay.

One possible explanation for your issue: when the iOS app is built, we upload 2 mapping files:
- native dsyms
- javascript sourcemaps

If you only disable dsyms, you will still attempt to upload the javascript sourcemaps. To disable all uploads in iOS builds you should use:

```json
{
    "expo": {
        "plugins": [
            [
                "expo-datadog",
                {
                    "errorTracking": {
                        "iosDsyms": false,
                        "iosSourcemaps": false
                    }
                }
            ]
        ]
    }
}
```

If you are still experiencing the issue, could you upload your iOS log to help us troubleshoot?

Thanks a lot!
