### ISSUE TITLE
[iOS] "No bundle URL present."

### ISSUE THREAD

**Issue by enlightenL** [DataDog/expo-datadog#31]
**Describe what happened**
When you add `expo-datadog` to `plugins` of `app.json` and then do a development build, the following error appears.
It works normally in the iPhone simulator and this only happens on the device.

<img src="https://github.com/DataDog/expo-datadog/assets/101613713/68eb71f0-53d9-4779-bc1c-ded341e3c210" width="600" />

**Steps to reproduce the issue:**
1. Install `@datadog/mobile-react-native` and `expo-datadog` as dependencies.
2. Install `@datadog/datadog-ci` as devDependencies.
3. Declare `DATADOG_APP_KEY` and `DATADOG_SITE` as environment variables, or place a `datadog-ci.json` file containing `appKey` and `datadogSite` properties in the project root.
4. Add `expo-datadog` to `plugins` in `app.json` and run `npx expo run:ios` to build.
5. After a successful build, the app will be installed. And immediately the app opens and an error occurs.

**Describe what you expected:**

A percent number appears as shown below, and bundling should proceed.

<img src="https://github.com/DataDog/expo-datadog/assets/101613713/b7a48ec3-59ee-4d3d-9fd4-d8b7bebc1d0d" width="600" />

**Additional context**

- `react@18.2.0`
- `react-native@0.73.5`
- `expo@50.0.13`
- `@datadog/mobile-react-native@2.2.0`
- `expo-datadog@50.2.0`
- `@datadog/datadog-ci@2.32.0`

**app.json**

```json
{
  "expo": {
    "name": "expo-datadog-test",
    "slug": "expo-datadog-test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.hello.expo-datadog-test"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      "expo-datadog"
    ],
    "experiments": {
      "typedRoutes": true
    }
  }
}
```

**Comment by louiszawadzki** [comment]
Hi @enlightenL, 

This issue seems unrelated to our Expo plugin, could you check if the error is solved when you remove `"expo-datadog"` from the list of expo plugins?
Let us know if this is the case.

If not, this might be related to the conditions needed to be able to run the development app on your device. 
If you are using the same wi-fi network on your device and your computer, restrictions might prevent your device from accessing the bundler. You can see how to bypass this [here](https://docs.expo.dev/develop/development-builds/development-workflows/).

**Comment by enlightenL** [comment]
@louiszawadzki

If you remove the `expo-datadog` expo plugin and do a development build, it will be bundled successfully. This issue appears to occur on all iPhones and all network environments. (Actually tested with iPhone 14 and iPhone SE in two network environments.)

Thank you.

**Comment by louiszawadzki** [comment]
Hi @enlightenL,

Thanks a lot for your report, I've been able to reproduce the issue and identify a fix.

It might take a few days for it to be released, so in the meantime you can use this patch for `@datadog/datadog-ci` using [patch-package](https://github.com/ds300/patch-package) to get unblocked:

```js
diff --git a/node_modules/@datadog/datadog-ci/dist/commands/react-native/xcode.js b/node_modules/@datadog/datadog-ci/dist/commands/react-native/xcode.js
index 95876f7..623d3ef 100644
--- a/node_modules/@datadog/datadog-ci/dist/commands/react-native/xcode.js
+++ b/node_modules/@datadog/datadog-ci/dist/commands/react-native/xcode.js
@@ -236,6 +236,7 @@ class XCodeCommand extends clipanion_1.Command {
             return !!podfileLockContent.match('hermes-engine');
         };
         this.shouldUploadSourcemaps = () => process.env.CONFIGURATION === 'Release' || this.force;
+        this.shouldBundle = () => process.env.CONFIGURATION === 'Release' || this.force || !process.env.PLATFORM_NAME?.match('simulator');
     }
     execute() {
         return __awaiter(this, void 0, void 0, function* () {
@@ -273,13 +274,17 @@ class XCodeCommand extends clipanion_1.Command {
             if (releaseVersion === null || buildVersion === null) {
                 return 1;
             }
-            if (!this.shouldUploadSourcemaps()) {
-                this.context.stdout.write(`Build configuration ${process.env.CONFIGURATION} is not Release, skipping sourcemaps upload`);
-                return 0;
-            }
+
             // Run bundle script
             try {
-                yield this.bundleReactNativeCodeAndImages();
+                if (this.shouldBundle()) {
+                    yield this.bundleReactNativeCodeAndImages();
+                }
+
+                if (!this.shouldUploadSourcemaps()) {
+                    this.context.stdout.write(`Build configuration ${process.env.CONFIGURATION} is not Release, skipping sourcemaps upload`);
+                    return 0;
+                }
                 /**
                  * Because of a bug in React Native (https://github.com/facebook/react-native/issues/34212), the composition
                  * of the 2 Hermes sourcemaps is not done correctly. Therefore we need to do the composition ourselves to
```

I will let you know in this issue once the release is out.

**Comment by enlightenL** [comment]
Thank you so much!! @louiszawadzki

The application will run and bundling will proceed successfully.

**Comment by enlightenL** [comment]
Hi @louiszawadzki,

It seems like the issue has come back again. This seems to happen in almost all versions of `@datadog/datadog-ci` (2.32.2 to 2.37.0).

**Comment by louiszawadzki** [comment]
cc @marco-saia-datadog
